baseURL = "https://remini.dev/"
languageCode = "en-us"
title = "Roniel Valdez's Blog"

theme = "cactus"
copyright = "Roniel Valdez"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  css = ["css/override.css"]

  colortheme = "dark"
  rss = true

  # Home page settings
  description = "Ideas I get over time"
  mainSection = "posts"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5
  tagsOverview = false
  showProjectsList = false
  projectsUrl = "https://github.com/rem1niscence"

  dateFormat = "2006-01-02" #

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false
    # engine = "disqus"

  [[params.social]]
    name = "github"
    link = "https://github.com/rem1niscence"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/ronielvaldez/"
  # [[params.social]]
    # name = "email"
    # link = "email@email.com"
