name: Build and Release

on:
  push:
    branches:
      - build-workflow

jobs:
  build-release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: public
        path: public/

    - name: Delete existing release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: latest
        delete_release: true
        delete_tag: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Blog files
        tag: latest
        files: public
